sudo: false

language: php

env:
  global:
    - SS_ENVIRONMENT_TYPE="dev"

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env:
        - DB=MYSQL PHPUNIT_TEST=1 PHPCS_TEST=1
    - php: 7.1
      env:
        - DB=MYSQL PHPUNIT_TEST=1 PHPCS_TEST=1
    - php: 7.2
      env:
        - DB=MYSQL PHPUNIT_TEST=1 PHPCS_TEST=1
    - php: 7.3
      env:
        - DB=MYSQL PHPUNIT_TEST=1 PHPCS_TEST=1

before_script:
  # Init PHP
  - echo "SS_DATABASE_USERNAME=\"root\"\nSS_DATABASE_PASSWORD=\"\"" > ./.env
  - composer self-update || true
  - phpenv rehash
  - phpenv config-rm xdebug.ini

  # Composer Deps
  - export PATH=~/.composer/vendor/bin:$PATH
  - composer validate
  - composer require silverstripe/recipe-cms
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml; fi
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs src test; fi

after_success:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml -F php; fi

branches:
  only:
    - master
    - 3.x
