---
Name: 'jsontext-config'
---

SilverStripe\Core\Injector\Injector:
  JSONText:
    class: \PhpTek\JSONText\ORM\FieldType\JSONText
    backend: postgres
  JSONTextExtension:
    class: \PhpTek\JSONText\Extensions\JSONTextExtension
